### ISSUE TITLE
cp command in makefile not working

### ISSUE THREAD

**Issue by tcrous** [schickling/Icomoon.swift#1]
According to Phlippie the cp command used in the first line of the make file will not work if you don't have gnu `cp`, please consider `ditto` instead

**Comment by schickling** [comment]
Absolutely. Would you be so kind and open a PR which checks if `cp` is available and falls back to `ditto` instead? :+1:

**Comment by phlippieb** [comment]
Actually, I think you could just default to `ditto`. AFAIK it's available on OSX by default. Otherwise `rsync -R` is also a good choice.

**Comment by schickling** [comment]
Sounds good! Do you mind opening a PR?

**Comment by phlippieb** [comment]
Created #3 to address this issue

**Comment by phlippieb** [comment]
#3 is merged, so I think this issue can be closed now 🍺
